import type { ThrowType } from "./combat";

/**
 * The numbers a throw's timing and its arm arc are made of, held in one mutable
 * object so the animation tool (`anim.html`) can edit them while the rig is on
 * screen and write them back to this file.
 *
 * Nothing here is new: it was inlined in `src/rigwalker.ts` as `THROW_BEATS`,
 * `THROW_ARM_KEYS` and the hurl's leg beats, and the prose that explains each
 * one has come across with it. What is new is that they are data rather than
 * constants, because a number you can only change by editing a file and
 * reloading is a number nobody tunes.
 *
 * Everything below the marker at the foot of this file is regenerated by the
 * tool's **Save**, so keep documentation up here where it survives a write.
 *
 * `tools/render_rigwalker_throw.py` hand-ports these numbers into Blender and
 * checks that the shipped values still trace the arc. It is a copy, not an
 * import — change anything here and that port has to follow, or the two
 * instruments start describing different animations.
 */

/** A beat of the motion: fades in over the first pair, out over the second. */
export type Beat = [number, number, number, number];

/**
 * The drive behind every throw: coil away, open, whip through, follow through.
 * The three throws differ in when these land and how far they go, not in which
 * bones they use.
 *
 * - `hurl` is a long wind: a full coil, a stride that opens the hips while the
 *   shoulders stay shut, then everything unwinds at once. Its whip peaks on the
 *   release phase, so the body is squarest to the target at the moment the rock
 *   leaves rather than after it.
 * - `pitch` has no stride and half the coil: a shoulder pitch thrown off a
 *   planted stance.
 * - `toss` is barely a wind at all — the arm is up and gone before the body has
 *   moved — and it keeps moving through the whole recovery, because a flick that
 *   freezes after the release reads as a dropped frame at RTS scale.
 */
export type ThrowDriveBeats = { draw: Beat; stride: Beat; whip: Beat; follow: Beat };

/**
 * One pose of the throwing arm, as offsets from the imported rest pose.
 *
 * The rest of the body is driven by beats, summing a coefficient per bone. The
 * throwing arm cannot be: the shoulder only holds the arm above shoulder height
 * through a narrow band of Euler angles, and summing a cocked pose against a
 * released one walks straight out of that band on the way between them. The arm
 * comes out hanging at the hip halfway through, which is exactly the dropped
 * elbow that made these throws read as sidearm. Keys placed along the arc keep
 * the arm inside the band the whole way.
 *
 * Every key was solved against the imported skeleton for a written-down hand
 * and elbow position, by `tools/render_rigwalker_throw.py`.
 */
export type ThrowArmKey = {
  /** Phase this pose lands on. Keys run in order between the two ready poses. */
  at: number;
  upperX: number;
  upperY: number;
  upperZ: number;
  lowerX: number;
  handX: number;
};

/**
 * The legs' own beats, and this is why they have them: a foot must be off the
 * ground before it travels, or it skates. The body's four beats are about
 * power, and every time a foot was hung on one of them it started moving a
 * fraction before or after it had anywhere to go.
 *
 * - `tuck` folds the trailing knee before anything swings, so the foot leaves
 *   the ground where it stood rather than dragging out of the stance.
 * - `swing` then carries that leg through, under the body and up.
 * - `step` is the plant: out fast, and home over the *whole* recovery. Reusing
 *   the stride beat here snapped the lead foot back under the hips in a tenth
 *   of a second, which is a slide however good the rest of the pose is.
 * - `heel` lifts the rear heel just before `drive` extends that leg behind, for
 *   the same reason as `tuck`: the drag only reads as a drive if the foot is
 *   already up when it starts.
 * - `home` clears the lead foot on the way back, so the recovery is a step and
 *   not the fighter's foot being dragged home.
 * - `open` is the free arm getting out of the chest's way, which is the same
 *   rule one limb further up: a part has to be clear of the body before it
 *   swings through where the body is. Riding the whip is too late — the whip is
 *   the swing.
 */
export type HurlLegBeats = {
  tuck: Beat;
  swing: Beat;
  step: Beat;
  heel: Beat;
  drive: Beat;
  home: Beat;
  open: Beat;
};

/**
 * One angle of the free arm, as a sum of the beats driving it.
 *
 * The throwing arm is keyed and this one is summed, and the difference is not an
 * inconsistency. The throwing arm traces an arc through a narrow band of Euler
 * angles that a sum walks straight out of; the free arm has no arc to trace. It
 * is a counterweight — it lifts, folds across the chest, and is driven down and
 * back as the body untwists — and each of those is one beat pulling one joint.
 *
 * Which drives a throw actually has differs:
 *
 * - `wind` is the wind-up. A hurl reads it as the *larger* of draw and stride
 *   rather than their sum, because those two overlap and adding them lifts the
 *   arm over the head halfway through the wind. A pitch reads it as `draw`. A
 *   toss has no wind worth the name and leaves this at zero.
 * - `aim` is the settle before a throw, and only a hurl has one.
 * - `open` is `hurlLegs.open`, and only a hurl uses it. It exists because the
 *   opening has to **lead** the swing-back: held across the chest while the
 *   shoulder drove it down and back, the elbow went a quarter of a metre inside
 *   the torso. Riding the whip is too late, because the whip is the swing. It is
 *   the same rule the feet follow one limb down.
 *
 * Terms whose drive a throw does not have are left at zero, and the animation
 * tool hides them rather than offering a slider that does nothing.
 */
export type FreeArmAngle = {
  base: number;
  wind: number;
  whip: number;
  follow: number;
  aim: number;
  open: number;
};

/**
 * The free arm through one throw. `upperY` is not here because it is never
 * anything but zero: this arm swings in the plane of the body and across it, and
 * a twist at the shoulder only ever made it read as a shrug.
 *
 * `lowerZ` and `handX` are single numbers because they are constants in all
 * three throws — the forearm's roll and the wrist, set once so the hand reads as
 * a hand rather than tracking anything.
 */
export type FreeArmPose = {
  /** Shoulder, forward and up. */
  upperX: FreeArmAngle;
  /** Shoulder, carrying the whole arm across the centre line. */
  upperZ: FreeArmAngle;
  /** Elbow. */
  lowerX: FreeArmAngle;
  lowerZ: number;
  handX: number;
};

/**
 * What the free arm is given on top while the hurler is settled between throws,
 * scaled by how settled it is. This is the pose it holds for most of a fight —
 * the throw itself is under a second of a cycle over two seconds long — so it is
 * the one most worth getting right.
 *
 * The hand is carried up by the shoulder and across by its Z, not by folding the
 * elbow: a folded elbow at this height reads as a gesture rather than a guard.
 */
export type ReadyArm = {
  upperX: number;
  /** Added to `upperX` again as the aim settles. */
  upperAim: number;
  upperZ: number;
  lowerX: number;
};

export type PoseTuning = {
  /**
   * Bladed and settled: rock hand low at the hip, elbow loose. Shared by all
   * three throws deliberately — it is both ends of every arc and the pose a
   * hurler stands in between throws, so one copy is what stops a change of
   * throw jumping the arm.
   */
  ready: ThrowArmKey;
  throwBeats: Record<ThrowType, ThrowDriveBeats>;
  /**
   * The arc, one entry per pose the hand passes through *between* the ready
   * poses at either end: the rock gathers back and low, comes up cocked beside
   * the ear with the elbow already above the shoulder, tops out above the head,
   * leaves the hand out in front and high, then rides down and across the body.
   * The three throws trace the same arc, differing in how early they get there
   * and how far they carry it.
   *
   * The hurl's elbow is the story of it. It folds to a right angle by the top of
   * the wind, holds while the shoulder comes through, and then extends — the
   * lever opening late, after the midpoint, is where the speed comes from. At
   * release it is straight and the wrist is in line with it, so the whole arm is
   * one bar through the rock. An elbow still bent at release is a thrower
   * pushing rather than throwing, however good the rest of the pose looks.
   */
  armKeys: Record<ThrowType, ThrowArmKey[]>;
  /** The counterweight arm, which is summed rather than keyed. See `FreeArmAngle`. */
  freeArm: Record<ThrowType, FreeArmPose>;
  readyArm: ReadyArm;
  hurlLegs: HurlLegBeats;
};

/** Which drives a throw actually has. The rest of its terms stay at zero. */
export const FREE_ARM_DRIVES: Record<ThrowType, ReadonlyArray<keyof FreeArmAngle>> = {
  hurl: ["base", "wind", "whip", "follow", "aim", "open"],
  pitch: ["base", "wind", "whip", "follow"],
  toss: ["base", "whip", "follow"],
};

/** Trimmed, so a value nudged by a slider does not save as `0.30000000000000004`. */
function serializeNumber(value: number): string {
  return String(Number(value.toFixed(4)));
}

function serializeBeat(beat: Beat): string {
  return `[${beat.map(serializeNumber).join(", ")}]`;
}

function serializeArmKey(key: ThrowArmKey): string {
  return `{ at: ${serializeNumber(key.at)}, ` +
    `upperX: ${serializeNumber(key.upperX)}, ` +
    `upperY: ${serializeNumber(key.upperY)}, ` +
    `upperZ: ${serializeNumber(key.upperZ)}, ` +
    `lowerX: ${serializeNumber(key.lowerX)}, ` +
    `handX: ${serializeNumber(key.handX)} }`;
}

function serializeFreeArmAngle(angle: FreeArmAngle): string {
  return `{ ${(["base", "wind", "whip", "follow", "aim", "open"] as const)
    .map((name) => `${name}: ${serializeNumber(angle[name])}`).join(", ")} }`;
}

function serializeFreeArm(pose: FreeArmPose): string {
  return (["upperX", "upperZ", "lowerX"] as const)
    .map((name) => `      ${name}: ${serializeFreeArmAngle(pose[name])},\n`).join("") +
    `      lowerZ: ${serializeNumber(pose.lowerZ)},\n` +
    `      handX: ${serializeNumber(pose.handX)},\n`;
}

/**
 * Puts every number back to a tuning taken earlier — what the tool's **Revert**
 * does with the values the page loaded with.
 *
 * It copies whatever keys the object has rather than naming them, because the
 * version that named them shipped broken the moment the free arm was added:
 * `freeArm` and `readyArm` were not on the list, so reverting quietly left them
 * edited. A restore that has to be updated every time the shape grows is a
 * restore that will be wrong again.
 *
 * The clone matters as much as the assign. Handing over the same objects would
 * leave the next edit writing straight into what Revert is holding, and there
 * would be nothing to go back to.
 */
export function restorePoseTuning(source: PoseTuning, target: PoseTuning = POSE_TUNING): void {
  Object.assign(target, structuredClone(source));
}

/** Marks where a **Save** from the animation tool starts overwriting this file. */
export const TUNING_MARKER = "/* ANIM-TOOL — everything below is rewritten by anim.html. */";

/**
 * The tuning as the TypeScript that produced it, ready to be written back over
 * the tail of this file. Emitted in exactly the shape it is authored in, so a
 * save with nothing edited leaves the file byte for byte as it was.
 */
export function serializePoseTuning(tuning: PoseTuning = POSE_TUNING): string {
  const throwTypes: ThrowType[] = ["hurl", "pitch", "toss"];
  const beats = throwTypes.map((type) => {
    const drive = tuning.throwBeats[type];
    return `    ${type}: {\n` +
      (["draw", "stride", "whip", "follow"] as const)
        .map((name) => `      ${name}: ${serializeBeat(drive[name])},\n`).join("") +
      "    },\n";
  }).join("");
  const keys = throwTypes.map((type) =>
    `    ${type}: [\n` +
    tuning.armKeys[type].map((key) => `      ${serializeArmKey(key)},\n`).join("") +
    "    ],\n").join("");
  const freeArm = throwTypes.map((type) =>
    `    ${type}: {\n${serializeFreeArm(tuning.freeArm[type])}    },\n`).join("");
  const readyArm = (["upperX", "upperAim", "upperZ", "lowerX"] as const)
    .map((name) => `${name}: ${serializeNumber(tuning.readyArm[name])}`).join(", ");
  const legs = (["tuck", "swing", "step", "heel", "drive", "home", "open"] as const)
    .map((name) => `    ${name}: ${serializeBeat(tuning.hurlLegs[name])},\n`).join("");
  return `${TUNING_MARKER}\nexport const POSE_TUNING: PoseTuning = {\n` +
    `  ready: ${serializeArmKey(tuning.ready)},\n` +
    `  throwBeats: {\n${beats}  },\n` +
    `  armKeys: {\n${keys}  },\n` +
    `  freeArm: {\n${freeArm}  },\n` +
    `  readyArm: { ${readyArm} },\n` +
    `  hurlLegs: {\n${legs}  },\n};\n`;
}

/* ANIM-TOOL — everything below is rewritten by anim.html. */
export const POSE_TUNING: PoseTuning = {
  ready: { at: 0, upperX: -0.35, upperY: 0, upperZ: -0.3, lowerX: -0.45, handX: 0 },
  throwBeats: {
    hurl: {
      draw: [0, 0.26, 0.4, 0.56],
      stride: [0.26, 0.44, 0.58, 0.76],
      whip: [0.4, 0.58, 0.58, 0.82],
      follow: [0.58, 0.74, 0.86, 1],
    },
    pitch: {
      draw: [0, 0.2, 0.3, 0.44],
      stride: [0.18, 0.32, 0.44, 0.62],
      whip: [0.28, 0.44, 0.44, 0.68],
      follow: [0.44, 0.6, 0.84, 1],
    },
    toss: {
      draw: [0, 0.12, 0.18, 0.3],
      stride: [0.08, 0.18, 0.3, 0.46],
      whip: [0.18, 0.32, 0.32, 0.52],
      follow: [0.32, 0.46, 0.74, 0.95],
    },
  },
  armKeys: {
    hurl: [
      { at: 0.14, upperX: -0.89, upperY: 0.17, upperZ: -0.79, lowerX: 1.35, handX: 0.45 },
      { at: 0.3, upperX: -1.25, upperY: 1.62, upperZ: -1.23, lowerX: 1.57, handX: 0.55 },
      { at: 0.48, upperX: -1.6, upperY: 1.7, upperZ: -1.52, lowerX: 1.05, handX: 0.4 },
      { at: 0.58, upperX: -1.6, upperY: 1.56, upperZ: -1.5, lowerX: 0, handX: 0 },
      { at: 0.7, upperX: -0.98, upperY: 0.94, upperZ: -0.77, lowerX: 0.45, handX: 0.1 },
      { at: 0.85, upperX: -0.32, upperY: 0.5, upperZ: -0.2, lowerX: 1, handX: 0.25 },
    ],
    pitch: [
      { at: 0.1, upperX: -0.92, upperY: -0.14, upperZ: -1.16, lowerX: 1.3, handX: 0.45 },
      { at: 0.24, upperX: -1.5, upperY: 1.62, upperZ: -0.84, lowerX: 1.65, handX: 0.5 },
      { at: 0.38, upperX: -1.64, upperY: 1.68, upperZ: -1.67, lowerX: 1.1, handX: 0.3 },
      { at: 0.44, upperX: -1.33, upperY: 1.56, upperZ: -1.31, lowerX: 0.3, handX: -0.3 },
      { at: 0.58, upperX: -0.78, upperY: 1.1, upperZ: -0.69, lowerX: 0.6, handX: 0.05 },
      { at: 0.8, upperX: -0.32, upperY: 0.45, upperZ: -0.24, lowerX: 1, handX: 0.2 },
    ],
    toss: [
      { at: 0.16, upperX: -1.1, upperY: 0.6, upperZ: -1.56, lowerX: 1.75, handX: 0.55 },
      { at: 0.26, upperX: -1.69, upperY: 1.49, upperZ: -1.64, lowerX: 1.35, handX: 0.35 },
      { at: 0.32, upperX: -1.15, upperY: 1.44, upperZ: -1.26, lowerX: 0.65, handX: -0.2 },
      { at: 0.46, upperX: -0.63, upperY: 1.05, upperZ: -0.79, lowerX: 0.75, handX: 0.05 },
      { at: 0.7, upperX: -0.34, upperY: 0.4, upperZ: -0.32, lowerX: 0.95, handX: 0.2 },
    ],
  },
  freeArm: {
    hurl: {
      upperX: { base: -0.4, wind: -0.72, whip: 1.35, follow: 0.34, aim: -0.34, open: 0 },
      upperZ: { base: 0.16, wind: -0.24, whip: 0, follow: 0.2, aim: 0, open: 0.7 },
      lowerX: { base: -1.34, wind: 0.72, whip: -0.43, follow: 0.2, aim: 0.35, open: 0.01 },
      lowerZ: -0.05,
      handX: -0.06,
    },
    pitch: {
      upperX: { base: -0.32, wind: -0.3, whip: 0.75, follow: 0.5, aim: 0, open: 0 },
      upperZ: { base: -0.08, wind: 0, whip: 0, follow: 0.12, aim: 0, open: 0 },
      lowerX: { base: -0.18, wind: -0.04, whip: 0.55, follow: 0.45, aim: 0, open: 0 },
      lowerZ: -0.05,
      handX: -0.06,
    },
    toss: {
      upperX: { base: -0.34, wind: 0, whip: 0.3, follow: 0.2, aim: 0, open: 0 },
      upperZ: { base: -0.1, wind: 0, whip: 0, follow: 0, aim: 0, open: 0 },
      lowerX: { base: -0.22, wind: 0, whip: 0.3, follow: 0.2, aim: 0, open: 0 },
      lowerZ: -0.06,
      handX: -0.06,
    },
  },
  readyArm: { upperX: -0.42, upperAim: -0.18, upperZ: -0.18, lowerX: -0.1 },
  hurlLegs: {
    tuck: [0, 0.12, 0.3, 0.48],
    swing: [0.02, 0.3, 0.3, 0.48],
    step: [0.26, 0.46, 0.74, 1],
    heel: [0.34, 0.5, 0.6, 0.86],
    drive: [0.4, 0.58, 0.6, 0.86],
    home: [0.7, 0.8, 0.9, 1],
    open: [0.34, 0.5, 0.62, 0.86],
  },
};
